spring.application.name=CricketProgram
server.port=8085
#spring.datasource.url=jdbc:mysql://localhost:3306/cricket
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://acs.c34i46goqnqp.us-east-2.rds.amazonaws.com:3306/cricket
spring.datasource.username=admin
spring.datasource.password=AcsHyderabad
server.ssl.enabled=false
